version: '3.8'

services:
  # MySQL container
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: chatdb
      MYSQL_DATABASE: chatdb
    ports:
      - "3306:3306"
    networks:
      - chat-network
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data in a Docker volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  # FastAPI app container
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mysql://root:chatdb@mysql:3306/chatdb  # Use service name `mysql` to connect
      - SECRET_KEY=chat_app
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=*  # Added ALLOWED_ORIGINS for your app's CORS handling
      - APP_NAME=Chat Application
      - APP_VERSION=1.0.0
      - PYTHONPATH=/app
    depends_on:
      mysql:
          condition: service_healthy
    networks:
      - chat-network
    volumes:
      - .:/app  # Mount the app directory (optional for live changes during development)
    restart: on-failure

networks:
  chat-network:
    driver: bridge  # Use a bridge network to allow containers to communicate

volumes:
  mysql_data:
    driver: local  # Use a Docker volume to persist MySQL data
